# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-23 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161224_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='contact'),
        ),
        migrations.AddField(
            model_name='user',
            name='quote',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='quote'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True, verbose_name='gender'),
        ),
    ]
