# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20161224_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.IntegerField(blank=True, null=True, verbose_name='contact'),
        ),
    ]
